config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :posts do
    resources :comments
  end

  root to: 'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :comments
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(params[:comment].permit(:name, :comment))
    if current_user
      @comment.user_id = current_user.id
      @comment.name = current_user.name
    end
    @comment.save
    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:show, :update, :edit, :destroy]

  def index
    @posts = Post.all.order("created_at DESC")
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def show; end

  def update
    if @post.update
      redirect_to @post
    else
      render 'edit'
    end
  end

  def edit; end

  def destroy
    @post.destroy
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :content)
  end

  def find_post
    @post = Post.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.haml
.box
  %article.media
    .media-content.content
      %p
        %strong= comment.name
        = comment.comment

    = link_to 'Delete', [comment.post, comment], method: :delete, class: "button is-danger", data: { confirm: "Are you sure?" }

app/views/comments/_form.html.haml
= simple_form_for([@post, @post.comments.build]) do |f|
  .field
    .control
      = f.input :name, input_html: {class: 'input'}, wrapper: false, required: true, label_html: { class: 'label' } unless current_user # if user is signed in, their name is the comment's name

  .field
    .control
      = f.input :comment, input_html: {class: 'textarea'}, wrapper: false, label_html: { class: 'label' }

  = f.button :submit, 'Post New Comment', class: "button is-primary"

app/views/layouts/_alerts.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Calvin'sDemoBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <section class="hero is-primary is-medium">
      <!-- Hero head: will stick at the top -->
      <div class="hero-head">
        <nav class="navbar">
          <div class="container">
            <div class="navbar-brand">
              <%= link_to "Calvin's Demo Blog", root_path, class: "navbar-item" %>
              <span class="navbar-burger burger" data-target="navbarMenuHeroA">
                  <span></span>
                  <span></span>
                  <span></span>
                </span>
            </div>
            <div id="navbarMenuHeroA" class="navbar-menu">
              <div class="navbar-end">
                <div class="navbar-item">
                  <div class="buttons">
                    <%= link_to "Create New Post", new_post_path, class: "button is-primary navbar-item" unless !current_user || !current_user.admin || controller_name == 'posts' && action_name == 'new' %>
                    <% if !current_user %>
                      <strong><%= link_to 'Sign in', new_user_session_path, class: "button is-primary navbar-item" %></strong>
                      <strong><%= link_to 'Sign up', new_user_registration_path, class: "button is-link is-inverted is-outlined navbar-item" %></strong>
                    <% else %>
                      <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: "button is-link is-inverted is-outlined navbar-item" %>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </nav>
      </div>

      <!-- Hero content: will be in the middle -->
      <div class="hero-body">
        <div class="container has-text-centered">
          <h1 class="title">
            <%= yield :page_title %>
          </h1>
        </div>
      </div>
    </section>
    <%= render 'layouts/alerts' %>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.haml
.section
  = simple_form_for @post do |f|
    .field
      .control
        = f.input :title, input_html: {class: 'input'}, wrapper: false, label_html: { class: 'label' }

    .field
      .control
        = f.input :content, input_html: {class: 'textarea'}, wrapper: false, label_html: { class: 'label' }

    = f.button :submit, 'Create New Post', class: "button is-primary"

app/views/posts/edit.html.haml
- content_for :page_title, "Edit post"

= render 'form'

app/views/posts/index.html.haml
- content_for :page_title, "Index"

.section
  .container
    -@posts.each do |post|
      .card.card-content
        .media.media-content
          %p.title.is-4= link_to post.title, post
        .content
          = post.content
      %br
        -#
          .comment-count
            .tag.is-rounded

app/views/posts/new.html.haml
- content_for :page_title, "Create a new post"

- if current_user && current_user.admin
  = render 'form'
- else
  .container.has-text-centered
    %h1.title Only an admin can create a post.
    .container
      = link_to 'Home', root_path, class: 'button'
      -if !current_user
        = link_to 'Sign in', new_user_session_path, class: 'button is-primary'

  

app/views/posts/show.html.haml
- content_for :page_title, @post.title

.section
  .container
    %nav.level
      - # left side
      .level-left
        %p.level-item
          %strong Actions
      - # right side
      .level-right
        %p.level-item= link_to "Edit", edit_post_path(@post), class: "button"
        %p.level-item= link_to "Delete", post_path(@post), method: :delete, data: {confirm: "Are you sure?"}, class: "button is-danger"
    %hr
    .content= @post.content

.section.comments
  .container
    %h2.subtitle.is-5
      %strong= @post.comments.count
      %strong Comments
    = render @post.comments
    .comment-form
      %hr
      %h3.subtitle.is-3 Leave a reply
      = render 'comments/form'